# Book settings
title:
author: Benjamin P. Stewart
logo: docs/images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/worldbank/Boundary_Comparison
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/Boundary_Comparison

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force
  allow_errors: true
  exclude_patterns:
    - notebooks/*.ipynb

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_last_updated_fmt: "%Y-%m-%d"
